<a href="https://colab.research.google.com/github/Laxmi1nayak/week_1/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#ARRAY CREATION
import numpy as np
# basic array
a = np.array([1,2,3])
print(a)
# range of values
b = np.arange(0,20,2)
print(b)

# evenly spaced values
c = np.linspace(0,10,5)
print(c)

#zeros and on
#2x2 matrix
d = np.zeros((2,3))
print(d)
#3x2 matrix
e = np.ones((3,2))
print(e)

 #identity matrix 3x3
f = np.eye(3)
print(f)


[1 2 3]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#INDEXING & SLICING
array=np.array([[10,20,30],[40,50,60]])
value=array[1,2]
print(value)


60


In [2]:
#SHAPE MANIPULATION
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
# Reshape
reshaped = x.reshape((2, 3))
print(x)

# Flatten
flat = x.flatten()
print(x)

# Transpose
transposed = x.T
print(x)


[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [4]:
#MATH OPERATION
data = np.array([[1, 2], [3, 4]])
print(data)
# Aggregates
mean_val = np.mean(data)
std_val = np.std(data)
sum_val = np.sum(data)
print(sum_val)

# Dot product
v1 = np.array([1, 2])
v2 = np.array([3, 4])
dot_product = np.dot(v1, v2)  # 11
print(dot_product)

# Matrix multiplication
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
matmul_result = np.matmul(m1, m2)
print(matmul_result)


[[1 2]
 [3 4]]
10
11
[[19 22]
 [43 50]]


In [5]:
#RANDOM MODULE
# Uniform random numbers
rand_vals = np.random.rand(2, 3)
print(rand_vals)

# Normal distribution
randn_vals = np.random.randn(2, 3)
print(rand_vals)

# Random integers
rand_ints = np.random.randint(0, 10, size=(2, 2))
print(rand_ints)

# Random choice
choices = np.random.choice([10, 20, 30], size=4)
print(choices)


[[0.13201079 0.15079935 0.29299744]
 [0.88061227 0.46932608 0.64125714]]
[[0.13201079 0.15079935 0.29299744]
 [0.88061227 0.46932608 0.64125714]]
[[9 5]
 [4 1]]
[20 30 20 20]
